/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class', // or 'media' - 'class' is usually more explicit for manual theme switching
  content: [
      "./pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./components/**/*.{js,ts,jsx,tsx,mdx}",
      "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
      extend: {
          colors: {
              // Serene Ocean Light Theme Palette
              light: {
                  primary: '#64B5F6',
                  primaryHover: '#42A5F5',
                  secondary: '#81C784',
                  secondaryHover: '#66BB6A',
                  accent: '#FFD54F',
                  accentHover: '#FFCA28',
                  backgroundPrimary: '#F8F9FA',
                  backgroundSecondary: '#ECEFF1',
                  backgroundAccent: '#E0E0E0',
                  textPrimary: '#424242',
                  textSecondary: '#757575',
                  textAccent: '#9E9E9E',
                  borderPrimary: '#BDBDBD',
                  borderSecondary: '#CFD8DC',
                  success: '#4CAF50',
                  error: '#F44336',
                  warning: '#FFC107',
                  info: '#03A9F4',
              },
              dark: {
                  primary: '#1E88E5',
                  primaryHover: '#1976D2',
                  secondary: '#26A69A',
                  secondaryHover: '#009688',
                  accent: '#FFEE58',
                  accentHover: '#FDD835',
                  backgroundPrimary: '#263238',
                  backgroundSecondary: '#37474F',
                  backgroundAccent: '#455A64',
                  textPrimary: '#ECEFF1',
                  textSecondary: '#B0BEC5',
                  textAccent: '#90A4AE',
                  borderPrimary: '#546E7A',
                  borderSecondary: '#607D8B',
                  success: '#4CAF50',
                  error: '#F44336',
                  warning: '#FFC107',
                  info: '#03A9F4',
              },
              // Top-level color definitions using CSS variables - Corrected syntax
              primary: 'rgb(var(--color-primary) / <alpha-value>)',
              primaryHover: 'rgb(var(--color-primary-hover) / <alpha-value>)',
              secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
              secondaryHover: 'rgb(var(--color-secondary-hover) / <alpha-value>)',
              accent: 'rgb(var(--color-accent) / <alpha-value>)',
              accentHover: 'rgb(var(--color-accent-hover) / <alpha-value>)',
              backgroundPrimary: 'rgb(var(--color-background-primary) / <alpha-value>)',
              backgroundSecondary: 'rgb(var(--color-background-secondary) / <alpha-value>)',
              backgroundAccent: 'rgb(var(--color-background-accent) / <alpha-value>)',
              textPrimary: 'rgb(var(--color-text-primary) / <alpha-value>)',
              textSecondary: 'rgb(var(--color-text-secondary) / <alpha-value>)',
              textAccent: 'rgb(var(--color-text-accent) / <alpha-value>)',
              borderPrimary: 'rgb(var(--color-border-primary) / <alpha-value>)',
              borderSecondary: 'rgb(var(--color-border-secondary) / <alpha-value>)',
              success: 'rgb(var(--color-success) / <alpha-value>)',
              error: 'rgb(var(--color-error) / <alpha-value>)',
              warning: 'rgb(var(--color-warning) / <alpha-value>)',
              info: 'rgb(var(--color-info) / <alpha-value>)',
          },
          animation: {
              'bounce': 'bounce 1.5s infinite',
              'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite'
          },
          fontFamily: {
              inter: ["Inter", "sans-serif"],
          },
      },
  },
  plugins: [require('@tailwindcss/typography')],
};